version: '3'

services:
  nuxt:
    ? image
    build: .
    environment:
      - ENV=development_docker
    container_name: web
    restart: always
    ports:
      - '3000:3000'
    command: 'npm run dev -- --spa'
